[tool.poetry]
name = 'faucet-rgb'
version = '0.1.0'
description = 'RGB faucet'
authors = ['Zoe Faltibà <zoefaltiba@gmail.com>', 'Nicola Busanello <nicola.busanello@gmail.com>']
license = 'MIT'

[tool.poetry.dependencies]
Flask = '^3.0.2'
Flask-APScheduler = "^1.13.1"
flask-migrate = "^4.0.5"
flask-sqlalchemy = "^3.1.1"
python = '^3.9'
rgb-lib = '0.2.0'

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
pylint = "^3.0.3"
toml = "^0.10.2"
yapf = "^0.40.2"
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
setuptools = "69.1.0"
flake8 = "^7.0.0"
vulture = "^2.11"

[tool.poetry.group.production.dependencies]
waitress = "^3.0.0"

[tool.poetry.group.scripts.dependencies]
rich = "^13.7.0"

[tool.isort]
filter_files = true
include_trailing_comma = false
multi_line_output = 4

[tool.vulture]
min_confidence = 100

[tool.yapf]
based_on_style = 'pep8'
split_penalty_import_names = 1000

[build-system]
requires = ['poetry-core>=1.0.0']
build-backend = 'poetry.core.masonry.api'

[tool.poetry.scripts]
issue-asset = 'issue_asset:entrypoint'
wallet-helper = 'wallet_helper:entrypoint'
